name: Java Static Analysis

on: [push, pull_request]

jobs:
  inspect-code:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Setup PMD
        run: |
          wget https://github.com/pmd/pmd/releases/download/pmd_releases%2F6.55.0/pmd-bin-6.55.0.zip
          unzip pmd-bin-6.55.0.zip
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}
      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew
  
      - name: Run SpotBugs
        run: ./gradlew spotbugsMain
        continue-on-error: true

      - name: Run Checkstyle
        run: ./gradlew checkstyleMain
        continue-on-error: true

      - name: PMD
        run: |
          ./pmd-bin-6.55.0/bin/run.sh pmd -d src/main/java -R rulesets/java/quickstart.xml -f text > pmd-report.txt
          if [ -s pmd-report.txt ]; then
            echo "PMD found issues:"
            cat pmd-report.txt
            echo "::warning::PMD found code quality issues"
          else
            echo "PMD check passed!"
          fi
        continue-on-error: true
