name: Java Static Analysis

on: [push, pull_request]

jobs:
  inspect-code:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      
      - name: Setup PMD
        run: |
          wget https://github.com/pmd/pmd/releases/download/pmd_releases%2F6.55.0/pmd-bin-6.55.0.zip
          unzip pmd-bin-6.55.0.zip

      - name: PMD
        run: |
          ./pmd-bin-6.55.0/bin/run.sh pmd -d src/main/java -R rulesets/java/quickstart.xml -f text > pmd-report.txt
          if [ -s pmd-report.txt ]; then
            echo "PMD found issues:"
            cat pmd-report.txt
            echo "::warning::PMD found code quality issues"
          else
            echo "PMD check passed!"
          fi
        continue-on-error: true
      
      - name: SpotBugs
        run: mvn spotbugs:check || echo "::warning::SpotBugs found potential bugs, check reports"
        continue-on-error: true
      
      - name: Checkstyle
        run: mvn checkstyle:check || echo "::warning::Checkstyle found code style issues"
      
